version: '3'
services:
  web:
    build: .
    ports: 
      - "5000:5000"
  postgres_db:
    image: "postgres:latest"
    container_name: "postgres_db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5533:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data