version: '3'
services:
  web:
    build: .
    ports: 
      - "5000:5000"
  postgres_db:
    image: "postgres:latest"
    container_name: "postgres_ponto"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=company
    ports:
      - "5432:5432"